[workspace]

members = [
"shinobi-core",
"shinobi-tauri/src-tauri"
]


[profile.release]
lto="fat"
codegen-units = 1
debug = false

[profile.release.package.shinobi-core]
#codegen-units = 1

#[dev-dependicies]
#criterio = {version = "0.4", features = ["html_reports"]}
