[workspace]

members = [
"shinobi-gui",
"shinobi-core"
]


[profile.release]
lto="fat"

[profile.release.package.shinobi-core]
codegen-units = 1

#[dev-dependicies]
#criterio = {version = "0.4", features = ["html_reports"]}
