[package]
name = "shinobi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
rand = "0.8.5"
sdl2 = "0.35.2"
strum = "0.24.1"
strum_macros = "0.24.3"

[[examples]]
name = "main"
